### ISSUE TITLE
Fails for example Level/leveldown

### ISSUE THREAD

**Issue by joelpurra** [mathiask88/prebuild-stats#1]
Using `npx` for simplicity.

```shell
npx prebuild-stats Level/leveldown
```

```text
npx: installed 10 in 1.748s
/home/joelpurra/.npm/_npx/49943/lib/node_modules/prebuild-stats/index.js:47
    const [name, version, runtime, abi, platform, arch] = regex.exec(asset.name).slice(1)
                                                                                ^

TypeError: Cannot read property 'slice' of null
    at /home/joelpurra/.npm/_npx/49943/lib/node_modules/prebuild-stats/index.js:47:81
    at Array.forEach (<anonymous>)
    at /home/joelpurra/.npm/_npx/49943/lib/node_modules/prebuild-stats/index.js:45:15
    at /home/joelpurra/.npm/_npx/49943/lib/node_modules/prebuild-stats/node_modules/simple-get/index.js:84:7
    at PassThrough.<anonymous> (/home/joelpurra/.npm/_npx/49943/lib/node_modules/prebuild-stats/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:417:28)
    at PassThrough.emit (events.js:311:20)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

It seems the format of the asset names have changed. This is the first time I'm using the tool, so unsure if it's only `Level/leveldown` or a more general change in upstream tools.

- https://github.com/prebuild/prebuild-stats/blob/e9859ab64d11c1d68614b99e152dc8895ee3b1fa/index.js#L46-L47
- https://github.com/Level/leveldown/blob/v5.6.0/package.json

Verifying github's api response on the command line using `curl` and `jq`. The `latest` release is `v5.6.0`; hardcoding for posterity.

- https://stedolan.github.io/jq/

```shell
curl --silent 'https://api.github.com/repos/Level/leveldown/releases/v5.6.0' | jq '.assets[].name'
```

```json
"v5.6.0-arm.tar.gz"
"v5.6.0-darwin-x64.tar.gz"
"v5.6.0-linux-x64.tar.gz"
"v5.6.0-win32-x64.tar.gz"
"v5.6.0-win32-x86.tar.gz"
```

Surely the naming format can be dynamically detected for upstream defaults, just not sure if there are "reliable" (non-customizable) defaults or if the naming format is commonly customized.

**Comment by vweevers** [comment]
This tool was designed for `prebuild(-install)`, but `leveldown` uses `prebuildify` & `node-gyp-build` since v5.

**Comment by vweevers** [comment]
And because of that, `leveldown` no longer downloads prebuilds, they are embedded in the npm package, so download stats for individual prebuilds are no longer available.

**Comment by joelpurra** [comment]
In that case I guess the repository in the example command should be updated.

- https://github.com/prebuild/prebuild-stats/blob/e9859ab64d11c1d68614b99e152dc8895ee3b1fa/README.md#L21-L23

Am personally not familiar enough with the tools to suggest a replacement.

**Comment by vweevers** [comment]
We can replace it with any of the dependents listed here: https://www.npmjs.com/package/prebuild-install?activeTab=dependents. The most popular addon is `sharp`, let's use that.

A PR is welcome!
